### ISSUE TITLE
[Question] Could this be used to develop cross platform webapps?

### ISSUE THREAD

**Issue by japrogramer** [makepad/makepad.github.io#10]
Hello, im very novice js developer, mostly focused on python, however I saw the video presentation for this library in youtube and was impressed by its performance.

Because the examples shown in the video where eluded to work on mobile, and I have tried it they do, 
couldn't than webgl with a wrapping library be used to develop apps that run native .. I mean that they can than be installed thru the app stores of its respected platform.

**Comment by makepaddev** [comment]
Thats not what im focussing makepad on. The goal of makepad is to create a fun programming environment for small games, toys and graphical experiments first and foremost, and run on Web. You can, technically, do what you said but it would be a fair amount of work since the thread architecture is rather important to makepad.
